### ISSUE TITLE
プレイヤー一覧ページ

### ISSUE THREAD

**Issue by rakou1986** [rakou1986/tamahiyo#1]
ソート
- レート
- 先月比
- 名前
- 参戦数
- 勝ち数
- 負け数
- 勝率
- 連勝数

フィルター
- 活動中（最後のプレイがｘ日前までの人）
- 凍結済みの人を除く
- 参戦ｘ回以上

**Comment by rakou1986** [comment]
名前が一番左がいいかも
横幅が長すぎない方がいいかも

**Comment by rakou1986** [comment]
先月比+の場合は、＋符号があったほうがいいかも

**Comment by rakou1986** [comment]
デフォルトは30日以内で

**Comment by kouchasan** [comment]
参戦期間は、今日、7日、30日、60日くらいから選べるといいかも

**Comment by kouchasan** [comment]
連勝、連敗の文字色は勝敗の文字色と統一してておｋ

**Comment by kouchasan** [comment]
偏差値ほしい

**Comment by rakou1986** [comment]
名前で検索したい

**Comment by rakou1986** [comment]
絞り込み条件をリセットするボタン

**Comment by rakou1986** [comment]
「絞り込み条件」という説明書きがいる

**Comment by rakou1986** [comment]
ｎ日以内に参戦した　というフィルターがあるが、
それを過去7日、30日、60日、全部の4択にして、
7日、30日、60日の場合は期間内の参戦数と勝率を出すとよさそう

**Comment by rakou1986** [comment]
過去7日、30日、60日の勝率

**Comment by rakou1986** [comment]
偏差値（フィルター後に再計算）

**Comment by rakou1986** [comment]
連勝の時の水色の文字が見づらいから、勝敗の数値と同じ色の青で

**Comment by kouchasan** [comment]
連敗の時の赤い字も勝敗の数値と同じ赤でよろろん

**Comment by rakou1986** [comment]
#1 の予定分は終了。
長くなったのでCloseして、追加分は別にIssueを立てます。

**Comment by rakou1986** [comment]
追加分は #15 #16 #17 #18 #19 で管理
